apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-service
  template:
    metadata:
      labels:
        app: eureka-service
    spec:
      containers:
        - name: eureka-service
          image: ijynx1/eureka-service:latest
          ports:
            - containerPort: 8761
          env:
            - name: status.podIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP